name: plantapp_case
description: HUBX - PlantApp
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^8.0.2
  injectable: ^2.5.0
  auto_route: ^9.2.2
  dio: ^5.7.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  shared_preferences: ^2.3.3
  google_fonts: ^6.1.0
  easy_localization: ^3.0.7
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  auto_route_generator: ^9.0.0
  injectable_generator: ^2.6.2
  flutter_lints: ^5.0.0
  mocktail: ^1.0.0
  bloc_test: ^9.1.5
  shared_preferences_platform_interface: ^2.4.1
  widgetbook: ^3.8.0
  widgetbook_annotation: ^3.2.0
  device_frame_plus: ^1.5.0


flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/icons/
    - assets/images/